from pydantic import BaseModel, ConfigDict
from typing import Optional, Dict
from enum import Enum


class VideoStatus(str, Enum):
    not_started = "not_started"
    in_progress = "in_progress"
    completed = "completed"
    failed = "failed"


# ---------------------------------------------------------
# REQUEST MODELS (from frontend)
# ---------------------------------------------------------

class VideoResponseRequest(BaseModel):
    application_id: str
    question_id: str
    transcript: Optional[str] = None
    duration: Optional[int] = None
    ai_analysis: Optional[Dict] = None
    status: Optional[VideoStatus] = VideoStatus.not_started
    recorded_at: Optional[str] = None  # ISO datetime string

    # video_url is generated by backend
    model_config = ConfigDict(from_attributes=True)


class GeneralVideoInterviewRequest(BaseModel):
    status: VideoStatus = VideoStatus.not_started
    ai_analysis: Optional[Dict] = None
    created_at: Optional[str] = None  # ISO datetime string

    # candidate_id is taken from request.state.user
    model_config = ConfigDict(from_attributes=True)


# ---------------------------------------------------------
# RESPONSE MODELS (to frontend)
# ---------------------------------------------------------

class VideoResponse(BaseModel):
    id: str
    application_id: str
    question_id: str
    video_url: Optional[str] = None
    transcript: Optional[str] = None
    duration: Optional[int] = None
    ai_analysis: Optional[Dict] = None
    status: VideoStatus
    recorded_at: Optional[str] = None

    model_config = ConfigDict(from_attributes=True)


class GeneralVideoInterview(BaseModel):
    id: str
    candidate_id: str
    video_url: Optional[str] = None
    status: VideoStatus
    ai_analysis: Optional[Dict] = None
    created_at: Optional[str] = None

    model_config = ConfigDict(from_attributes=True)
